# docker-compose.yml

version: '3.8'

services:
  # Service 1: The MLflow Tracking Server
  mlflow-server:
    build:
      context: .
      dockerfile: mlflow.Dockerfile
    ports:
      # Expose the MLflow UI on your machine at port 5002
      - "5002:5000"
    volumes:
      # This makes the MLflow data (your models) persistent across restarts
      - ./mlruns:/mlruns
    networks:
      - ml-network

  # Service 2: The Flask API
  api:
    # This is the crucial line. It tells docker-compose to use your
    # official image from Docker Hub for this service during deployment.
    image: apurbaghosh363/iris-mlops-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    depends_on:
      - mlflow-server
    volumes:
      # This makes the API's logs persistent
      - ./logs:/app/logs
    networks:
      - ml-network

# Define the private network for the containers to communicate
networks:
  ml-network:
    driver: bridge
