# File: .github/workflows/ci-cd.yml

name: MLOps CI/CD Pipeline

# This workflow runs on any push to the 'main' or 'master' branch
on:
  push:
    branches:
      - main
      - master

jobs:
  # Job 1: Linting and basic checks
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8  # Install the linter

      - name: Lint with flake8
        run: |
          # Run flake8 to check for code style issues and potential errors
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  
  # Job 2: Build the Docker image and push to Docker Hub
  build-and-push:
    # This job will only run if the 'lint-and-test' job completes successfully
    needs: lint-and-test 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image for the API
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile # Path to the API's Dockerfile
          push: true
          # The tag will be something like: your-dockerhub-username/iris-mlops-api:latest
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/iris-mlops-api:latest